# Generated by Django 5.1.6 on 2025-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverify',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
