# Generated by Django 5.1.6 on 2025-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='area',
            field=models.CharField(choices=[('one', 'One (20 sqm)'), ('two', 'Two (40 sqm)'), ('three_plus', 'Three or More (60 sqm)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit`card', 'Debit Card'), ('paypal', 'PayPal')], max_length=12, null=True),
        ),
    ]
