# Generated by Django 5.1.6 on 2025-02-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_area_alter_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
    ]
